project:
  group: slipper
  name: slipper

service:
  port: 8808
  context-path: /slipper

database:
  ip: 139.196.182.46
  port: 3306
  name: im
  username: root
  password: ll5271211314

druid:
  url-pattern: /druid/*
  username: gumingchen
  password: gumingchen

token:
  expire: 36000

redis:
  host: localhost
  port: 6379
  password:

netty:
  port: 8809
  url: ws://localhost:${netty.port}/websocket/{token}
